[config]

[config.wallpaper]
set = false
command = "swww"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/matugen/generated/hypr-colors.conf'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/matugen/generated/rofi-colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/matugen/generated/colors.css'
post_hook = 'pkill waybar; waybar & disown; pkill cava.sh;'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/matugen/generated/colors.css'
post_hook = 'pkill swaync; swaync & disown'

[templates.swayosd]
input_path = '~/.config/matugen/templates/swayosd-colors.css'
output_path = '~/.config/matugen/generated/swayosd-colors.css'
post_hook = '~/.config/swayosd/scripts/restartOSD.sh'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/matugen/generated/btop.theme'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/matugen/generated/qtct-colors.conf'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/matugen/generated/cava-colors.ini'
post_hook = 'mkdir -p $HOME/.config/cava/themes; ln -nfs $HOME/.config/matugen/generated/cava-colors.ini $HOME/.config/cava/themes/cava-colors.ini; pkill -USR1 cava || true'

# [templates.yazi]
# input_path = '~/.config/matugen/templates/yazi-theme.toml'
# output_path = '~/.config/matugen/generated/yazi-theme.toml'
# post_hook = 'ln -nfs $HOME/.config/matugen/generated/yazi-theme.toml $HOME/.config/yazi/theme.toml' 