# â”Œâ”€â”â”Œâ”¬â”â”Œâ”€â”â”¬â”€â”â”Œâ”€â”â”¬ â”¬â”¬â”Œâ”€â”
# â””â”€â” â”‚ â”œâ”€â”¤â”œâ”¬â”˜â””â”€â”â”œâ”€â”¤â”‚â”œâ”€â”˜
# â””â”€â”˜ â”´ â”´ â”´â”´â””â”€â””â”€â”˜â”´ â”´â”´â”´  


"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """[ó°•](fg:blue) $directory\ 
 $git_branch\
 $git_status \
 [ïƒ§](fg:yellow)\
 $fill\
 $lua\
 $nodejs\
 $rust\
 $python\
 $docker_context\   
 $jobs\
 $cmd_duration\
 $line_break\
 $character"""

[username]
show_always = true
style_user = "bold fg:#00F5FF"
format = "[$user]($style)"

[fill]
symbol = " "

[character]
success_symbol = "[â–¶](bold fg:#7C9FF3)"
error_symbol = "[â–¶](bold red)"

[directory]
style = "fg:#769ff0"
format = "$path"
truncation_length = 1
truncation_symbol = ""

[jobs]
symbol = "ó±¸"

[directory.substitutions]
"Desktop" = "ï’© "
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "îœ¥"
style = "fg:cyan"
format = '[ $branch $symbol ]($style)'

[git_status]
conflicted = " ğŸ³ "
ahead = " ó±¨ "
behind = " ó±¦ "
diverged = " ó°¦» "
untracked = " î¯š "
stashed = " ï“ "
modified = " î°‹ "
staged = '[++\($count\)](green)'
renamed = " ó°‘• "
deleted = " ó°—© "

[git_commit]
commit_hash_length = 4
tag_symbol = " ï’¶ "

[time]
disabled = true
time_format = "%R"
style = "fg:#0D4A88"
format = "$time"

[cmd_duration]
disabled = false
min_time = 500
format = "[ó±¤¤ $duration]($style)"
style = "fg:yellow"

[nodejs]
symbol = "îœ˜ "

[python]
symbol = "îœ¼ "

[rust]
symbol = "î¨ "

[lua]
symbol = "î˜  "
