# ┌─┐┌┬┐┌─┐┬─┐┌─┐┬ ┬┬┌─┐
# └─┐ │ ├─┤├┬┘└─┐├─┤│├─┘
# └─┘ ┴ ┴ ┴┴└─└─┘┴ ┴┴┴  


"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = """[󱝂](fg:#7C9FF3) $username $directory $git_branch$git_status $time $cmd_duration\n$character"""

[username]
show_always = true
style_user = "bold fg:green"
format = "[$user]($style)"


[character]
success_symbol = "[▶](bold fg:#7C9FF3)"
error_symbol = "[▶](bold red)"
vicmd_symbol = "[▶](bold yellow)"

[directory]
style = "fg:#769ff0"
format = "$path"
truncation_length = 1
truncation_symbol = ""

[git_branch]
symbol = ""
style = "fg:cyan"
format = '[ $branch $symbol ]($style)'

[git_status]
style = "fg:red"
format = '[($all_status$ahead_behind)]($style)'

[time]
disabled = true
time_format = "%R"
style = "fg:#0D4A88"
format = "$time"

[cmd_duration]
disabled = false
min_time = 500
format = "[󱤤 $duration]($style)"
style = "fg:yellow"

[nodejs]
disabled = false
[rust]
disabled = true
[golang]
disabled = true
[php]
disabled = true
